// Mock data for the BPA Platform
export const pendingApprovals = [
  {
    id: 'APR-2024-001',
    title: 'CapEx Request — Server Infrastructure Upgrade',
    requester: 'Sarah Chen',
    department: 'IT Operations',
    priority: 'P1',
    slaRemaining: '1h 45m',
    slaStatus: 'critical',
    amount: '$128,500',
    step: 'VP Approval (Step 3/4)',
    submittedAt: '2 hours ago',
    type: 'Capital Expenditure',
  },
  {
    id: 'APR-2024-002',
    title: 'Vendor Onboarding — Acme Cloud Services',
    requester: 'James Liu',
    department: 'Procurement',
    priority: 'P1',
    slaRemaining: '3h 20m',
    slaStatus: 'warning',
    amount: '$45,000/yr',
    step: 'Legal Review (Step 2/5)',
    submittedAt: '5 hours ago',
    type: 'Vendor Procurement',
  },
  {
    id: 'APR-2024-003',
    title: 'Elevated Access — Production Database (Read/Write)',
    requester: 'Michael Torres',
    department: 'Engineering',
    priority: 'P2',
    slaRemaining: '8h 10m',
    slaStatus: 'warning',
    amount: '—',
    step: 'Security Review (Step 2/3)',
    submittedAt: '1 day ago',
    type: 'IT Access Grant',
  },
  {
    id: 'APR-2024-004',
    title: 'Travel Request — AWS re:Invent Conference',
    requester: 'Emily Park',
    department: 'Engineering',
    priority: 'P3',
    slaRemaining: '22h 30m',
    slaStatus: 'ok',
    amount: '$4,200',
    step: 'Manager Approval (Step 1/2)',
    submittedAt: '3 hours ago',
    type: 'Travel Request',
  },
  {
    id: 'APR-2024-005',
    title: 'New Hire Onboarding — Data Analyst (Finance)',
    requester: 'HR Department',
    department: 'Human Resources',
    priority: 'P2',
    slaRemaining: '16h 00m',
    slaStatus: 'ok',
    amount: '—',
    step: 'IT Setup (Step 3/5)',
    submittedAt: '1 day ago',
    type: 'Employee Onboarding',
  },
  {
    id: 'APR-2024-006',
    title: 'Software License — Figma Enterprise (50 seats)',
    requester: 'Design Team',
    department: 'Product Design',
    priority: 'P3',
    slaRemaining: '36h 15m',
    slaStatus: 'ok',
    amount: '$18,000/yr',
    step: 'Budget Approval (Step 2/3)',
    submittedAt: '2 days ago',
    type: 'Software License',
  },
];

export const workflowCatalog = [
  // Manual
  { id: 'wf-1', name: 'Capital Expenditure Request', desc: 'Submit CapEx proposals for budget approval with multi-tier sign-off', trigger: 'manual', icon: 'DollarSign', category: 'Finance' },
  { id: 'wf-2', name: 'Travel Authorization', desc: 'Request approval for business travel with expense pre-approval', trigger: 'manual', icon: 'Plane', category: 'Operations' },
  { id: 'wf-3', name: 'Elevated Access Request', desc: 'Request temporary elevated system access with security review', trigger: 'manual', icon: 'KeyRound', category: 'IT Security' },
  { id: 'wf-4', name: 'Vendor Onboarding', desc: 'Initiate new vendor procurement with compliance verification', trigger: 'manual', icon: 'Handshake', category: 'Procurement' },
  { id: 'wf-5', name: 'Employee Onboarding', desc: 'Complete new hire setup across IT, HR, and department systems', trigger: 'manual', icon: 'UserPlus', category: 'HR' },
  { id: 'wf-6', name: 'Change Request (ITIL)', desc: 'Submit change requests following ITIL change management process', trigger: 'manual', icon: 'RefreshCw', category: 'IT Operations' },
  // Cron
  { id: 'wf-7', name: 'Daily Data Integrity Check', desc: 'Automated midnight sweep to validate data consistency across systems', trigger: 'cron', icon: 'SearchCheck', category: 'Data Quality' },
  { id: 'wf-8', name: 'Weekly Reconciliation Run', desc: 'Financial reconciliation between ERP and banking systems', trigger: 'cron', icon: 'BarChart3', category: 'Finance' },
  { id: 'wf-9', name: 'License Compliance Scan', desc: 'Daily scan of software license usage against entitlements', trigger: 'cron', icon: 'ClipboardCheck', category: 'Compliance' },
  // Webhook
  { id: 'wf-10', name: 'SAP Invoice Alert', desc: 'Triggered when SAP flags an unpaid invoice past due date', trigger: 'webhook', icon: 'MailWarning', category: 'Finance' },
  { id: 'wf-11', name: 'Cloud Security Alert', desc: 'Responds to AWS GuardDuty or Azure Sentinel security findings', trigger: 'webhook', icon: 'ShieldAlert', category: 'Security' },
  { id: 'wf-12', name: 'Git Deployment Gate', desc: 'Triggered by CI/CD pipeline for production deployment approvals', trigger: 'webhook', icon: 'Rocket', category: 'DevOps' },
  // One-Time
  { id: 'wf-13', name: 'Data Migration Pipeline', desc: 'One-time data migration between legacy and new systems', trigger: 'one-time', icon: 'PackageOpen', category: 'Migration' },
  { id: 'wf-14', name: 'Ad-Hoc Compliance Audit', desc: 'Single-run audit triggered by regulatory request', trigger: 'one-time', icon: 'FileSearch', category: 'Audit' },
];

export const myRequests = [
  {
    id: 'REQ-4821',
    title: 'CapEx — Marketing Automation Platform',
    status: 'in-progress',
    currentStep: 3,
    totalSteps: 4,
    steps: ['Submitted', 'Manager', 'VP Finance', 'CFO'],
    submittedAt: 'Sep 25, 2024',
    lastUpdate: '2 hours ago',
    assignedTo: 'VP Finance — Robert Kim',
  },
  {
    id: 'REQ-4819',
    title: 'Vendor Onboarding — DataDog Monitoring',
    status: 'in-progress',
    currentStep: 2,
    totalSteps: 5,
    steps: ['Submitted', 'Procurement', 'Legal', 'Security', 'Finance'],
    submittedAt: 'Sep 24, 2024',
    lastUpdate: '6 hours ago',
    assignedTo: 'Legal — Maria Santos',
  },
  {
    id: 'REQ-4815',
    title: 'Travel Request — QCon London 2024',
    status: 'approved',
    currentStep: 2,
    totalSteps: 2,
    steps: ['Submitted', 'Manager'],
    submittedAt: 'Sep 22, 2024',
    lastUpdate: '1 day ago',
    assignedTo: '—',
  },
  {
    id: 'REQ-4810',
    title: 'Access Request — Staging Kubernetes Cluster',
    status: 'rejected',
    currentStep: 2,
    totalSteps: 3,
    steps: ['Submitted', 'Security', 'IT Ops'],
    submittedAt: 'Sep 20, 2024',
    lastUpdate: '3 days ago',
    assignedTo: '—',
  },
  {
    id: 'REQ-4805',
    title: 'Employee Offboarding — Contract Developer',
    status: 'in-progress',
    currentStep: 4,
    totalSteps: 5,
    steps: ['HR Notice', 'Manager', 'IT Revoke', 'Finance', 'Complete'],
    submittedAt: 'Sep 18, 2024',
    lastUpdate: '1 day ago',
    assignedTo: 'Finance — Accounts Payable',
  },
];

export const controls = [
  {
    id: 'CTR-001',
    name: 'SOC2 Access Reviews — Quarterly',
    type: 'Information Security',
    icon: 'Lock',
    status: 'active',
    effectiveFrom: 'Jan 1, 2024',
    expiresAt: 'Dec 31, 2024',
    daysRemaining: 94,
    totalDays: 365,
    owner: 'You',
    health: 'healthy',
  },
  {
    id: 'CTR-002',
    name: 'ISO 27001 Policy — Data Classification',
    type: 'Compliance Policy',
    icon: 'FileText',
    status: 'renewal',
    effectiveFrom: 'Mar 15, 2024',
    expiresAt: 'Oct 28, 2024',
    daysRemaining: 25,
    totalDays: 228,
    owner: 'You',
    health: 'warning',
  },
  {
    id: 'CTR-003',
    name: 'AWS Enterprise License Agreement',
    type: 'Software License',
    icon: 'Cloud',
    status: 'active',
    effectiveFrom: 'Jun 1, 2024',
    expiresAt: 'May 31, 2025',
    daysRemaining: 248,
    totalDays: 365,
    owner: 'You',
    health: 'healthy',
  },
  {
    id: 'CTR-004',
    name: 'Vendor SLA — Acme Payment Gateway',
    type: 'Vendor SLA',
    icon: 'Handshake',
    status: 'breach',
    effectiveFrom: 'Feb 1, 2024',
    expiresAt: 'Oct 5, 2024',
    daysRemaining: 2,
    totalDays: 247,
    owner: 'You',
    health: 'critical',
  },
  {
    id: 'CTR-005',
    name: 'GDPR Data Privacy Impact Assessment',
    type: 'Privacy',
    icon: 'ShieldCheck',
    status: 'active',
    effectiveFrom: 'Apr 1, 2024',
    expiresAt: 'Mar 31, 2025',
    daysRemaining: 183,
    totalDays: 365,
    owner: 'You',
    health: 'healthy',
  },
  {
    id: 'CTR-006',
    name: 'Annual Compliance Attestation — Finance',
    type: 'Attestation',
    icon: 'BadgeCheck',
    status: 'renewal',
    effectiveFrom: 'Jan 1, 2024',
    expiresAt: 'Oct 15, 2024',
    daysRemaining: 12,
    totalDays: 288,
    owner: 'You',
    health: 'warning',
  },
];

export const cronSchedules = [
  {
    id: 'CRON-001',
    name: 'Daily Data Integrity Sweep',
    schedule: '0 0 * * *',
    frequency: 'Every day at midnight',
    status: 'active',
    lastRun: 'Today 00:00 UTC',
    lastResult: 'success',
    nextRun: 'Tomorrow 00:00 UTC',
    owner: 'You',
  },
  {
    id: 'CRON-002',
    name: 'Weekly Financial Reconciliation',
    schedule: '0 6 * * 1',
    frequency: 'Every Monday at 6:00 AM',
    status: 'active',
    lastRun: 'Sep 23, 6:00 AM',
    lastResult: 'success',
    nextRun: 'Sep 30, 6:00 AM',
    owner: 'You',
  },
  {
    id: 'CRON-003',
    name: 'License Usage Report',
    schedule: '0 8 * * *',
    frequency: 'Every day at 8:00 AM',
    status: 'paused',
    lastRun: 'Sep 20, 8:00 AM',
    lastResult: 'warning',
    nextRun: 'Paused',
    owner: 'You',
  },
  {
    id: 'CRON-004',
    name: 'Vendor SLA Compliance Check',
    schedule: '0 9 * * 1-5',
    frequency: 'Weekdays at 9:00 AM',
    status: 'active',
    lastRun: 'Today 09:00 UTC',
    lastResult: 'failure',
    nextRun: 'Tomorrow 09:00 UTC',
    owner: 'You',
  },
  {
    id: 'CRON-005',
    name: 'Monthly Access Review Reminder',
    schedule: '0 10 1 * *',
    frequency: 'First day of month at 10 AM',
    status: 'active',
    lastRun: 'Sep 1, 10:00 AM',
    lastResult: 'success',
    nextRun: 'Oct 1, 10:00 AM',
    owner: 'You',
  },
];

export const auditTrail = [
  {
    id: 'AUD-001',
    action: 'Approved',
    item: 'CapEx — Cloud Migration Phase 2',
    itemId: 'APR-2024-098',
    timestamp: 'Sep 28, 2024 · 2:15 PM',
    comment: 'Budget verified. Approved with condition: quarterly spend review required.',
    icon: 'CheckCircle2',
    color: 'success',
  },
  {
    id: 'AUD-002',
    action: 'Delegated',
    item: 'Vendor Onboarding — SecureAuth Inc.',
    itemId: 'APR-2024-095',
    timestamp: 'Sep 28, 2024 · 11:30 AM',
    comment: 'Delegated to Maria Santos (Legal) for contract review — out of office until Oct 2.',
    icon: 'ExternalLink',
    color: 'info',
  },
  {
    id: 'AUD-003',
    action: 'Rejected',
    item: 'Access Request — Production Write Access',
    itemId: 'APR-2024-091',
    timestamp: 'Sep 27, 2024 · 4:45 PM',
    comment: 'Denied: Insufficient justification. Read-only access granted as alternative.',
    icon: 'XCircle',
    color: 'danger',
  },
  {
    id: 'AUD-004',
    action: 'Approved',
    item: 'Travel — Berlin DevOps Summit',
    itemId: 'APR-2024-088',
    timestamp: 'Sep 27, 2024 · 10:00 AM',
    comment: 'Within budget. Approved.',
    icon: 'CheckCircle2',
    color: 'success',
  },
  {
    id: 'AUD-005',
    action: 'Comment Added',
    item: 'Employee Offboarding — J. Martinez',
    itemId: 'APR-2024-085',
    timestamp: 'Sep 26, 2024 · 3:20 PM',
    comment: 'Confirmed all access credentials have been revoked. IT sign-off complete.',
    icon: 'MessageSquare',
    color: 'neutral',
  },
  {
    id: 'AUD-006',
    action: 'Approved',
    item: 'Software License — JetBrains All Products Pack',
    itemId: 'APR-2024-082',
    timestamp: 'Sep 26, 2024 · 9:15 AM',
    comment: 'Approved for Engineering team (25 seats). Annual renewal.',
    icon: 'CheckCircle2',
    color: 'success',
  },
  {
    id: 'AUD-007',
    action: 'Escalated',
    item: 'CapEx — Physical Office Expansion',
    itemId: 'APR-2024-078',
    timestamp: 'Sep 25, 2024 · 2:00 PM',
    comment: 'Amount exceeds VP threshold ($250K). Escalated to C-Suite approval.',
    icon: 'ArrowUpCircle',
    color: 'warning',
  },
];

export const slaMetrics = {
  personalCompliance: 94.2,
  teamCompliance: 87.8,
  avgCycleTime: '18.5h',
  bottleneckDept: 'Legal Review',
  bottleneckAvg: '12.3h',
  monthlyTrend: [88, 91, 85, 93, 90, 94, 92, 96, 89, 94, 91, 95],
  byDepartment: [
    { dept: 'Finance', compliance: 96, avg: '14h' },
    { dept: 'IT Ops', compliance: 92, avg: '16h' },
    { dept: 'Legal', compliance: 78, avg: '28h' },
    { dept: 'HR', compliance: 95, avg: '12h' },
    { dept: 'Security', compliance: 88, avg: '20h' },
    { dept: 'Procurement', compliance: 91, avg: '18h' },
  ],
};
